name: sticky_grouped_list_plus
description: A ScrollablePositionedList where the list items can be grouped into sections.
version: 0.0.1
homepage: https://begnis.dev
repository: https://github.com/xaldarof/sticky_grouped_list

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  scrollable_positioned_list: ^0.3.2
  meta: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1